theme = "catppuccin_mocha_transparent"

[editor]
auto-format = false
bufferline = "always"
color-modes = true
cursorcolumn = true
cursorline = true
end-of-line-diagnostics = "hint"
line-number = "relative"
mouse = false
rulers = [150]
true-color = true

[editor.auto-save]
focus-lost = true
after-delay.enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "error"

[editor.lsp]
display-inlay-hints = true

[editor.statusline]
left = ["mode", "spinner", "diagnostics"]
center = ["file-name", "file-modification-indicator", "version-control"]
right = ["position", "total-line-numbers"]
mode.normal = "normal"
mode.insert = "insert"
mode.select = "select"

[keys.insert]
"esc" = ["collapse_selection", "normal_mode"]

[keys.normal]
"A-<" = "goto_previous_buffer"
"A->" = "goto_next_buffer"
"A-w" = ":buffer-close"
"X" = "select_line_above"
"esc" = ["collapse_selection", "keep_primary_selection"]

[keys.select]
"A-x" = "extend_to_line_bounds"
"X" = "select_line_above"
"esc" = ["collapse_selection", "keep_primary_selection", "normal_mode"]
